[book]
title        = "捷克足球裁判员训练的可持续创新"
authors      = ["zz"]
language     = "zh"
multilingual = false
src = "src"

[output.html]
mathjax-support = true
git-repository-url = "https://zzzxj12138.github.io/index/"
